name: CloudStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest
    steps:
      - name: "'src' Depo Kontrolü"
        uses: actions/checkout@v4.2.2
        with:
          path: "src"
          fetch-depth: 0

      - name: "'build' Depo Kontrolü"
        uses: actions/checkout@v4.2.2
        with:
          ref: "builds"
          path: "builds"
          fetch-depth: 0

      - name: Eski Derlemeleri Temizle
        run: |
          if [ -f "$GITHUB_WORKSPACE/builds/*.cs3" ]; then
            rm $GITHUB_WORKSPACE/builds/*.cs3
          else
            echo "Derleme dosyası bulunamadı, devam ediliyor."
          fi

      - name: JDK 17 Ayarla
        uses: actions/setup-java@v4.6.0
        with:
          distribution: adopt
          java-version: 17

      - name: Android SDK Ayarla
        uses: android-actions/setup-android@v3.2.2

      - name: Eklentileri Derle
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Derlemeleri Yükle
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "$GITHUB_SHA 'nın Derlenmesi" || exit 0
          git push --force-with-lease
