name: CloudStream Derleyici
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"
jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest
    steps:
      - name: "Kaynak Kod Kontrolü"
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          token: ${{ github.token }}
      - name: JDK 17 Ayarla
        uses: actions/setup-java@v4.6.0
        with:
          distribution: adopt
          java-version: 17
      - name: Android SDK Ayarla
        uses: android-actions/setup-android@v3.2.2
      - name: Eski Derlemeleri Temizle
        run: |
          if ls *.cs3 1> /dev/null 2>&1; then
            rm *.cs3
          fi
          if [ -f "plugins.json" ]; then
            rm plugins.json
          fi
      - name: Eklentileri Derle
        run: |
          chmod +x gradlew
          ./gradlew make makePluginsJson
      - name: Derlemeleri Yükle
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *.cs3 plugins.json
          git diff --staged --quiet || git commit -m "$GITHUB_SHA 'nın Derlenmesi"
          git pull --rebase origin master
          git push origin master
